name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: gradlew bootJar
        run: ./gradlew bootJar

      - name: copy jar to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./build/libs/*.jar"
          target: "~"
          strip_components: 2

      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            kill -9 $(ps -ef | grep java | head -n 1 | awk '{print $2}')
            nohup java -jar *.jar 1> /dev/null 2>&1 &

      - name: Set up environment variables
        run: |
          echo "spring.datasource.url=jdbc:mysql://spring-plus.c9eg486ec6h8.ap-northeast-2.rds.amazonaws.com:3306/spring_plus" >> application.properties
          echo "spring.datasource.username=root" >> application.properties
          echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> application.properties
          echo "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver" >> application.properties
          echo "spring.jpa.hibernate.ddl-auto=update" >> application.properties
          echo "spring.jpa.properties.hibernate.show_sql=true" >> application.properties
          echo "spring.jpa.properties.hibernate.format_sql=true" >> application.properties
          echo "spring.jpa.properties.hibernate.use_sql_comments=true" >> application.properties
          echo "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect" >> application.properties
          echo "s3.credentials.access-key=${{ secrets.ACCESS_KEY }}" >> application.properties
          echo "s3.credentials.secret-key=${{ secrets.SECRET_KEY }}" >> application.properties
          echo "s3.credentials.region=ap-northeast-2" >> application.properties
          echo "s3.bucket=${{ secrets.BUCKET }}" >> application.properties
          echo "jwt.secret.key=${{ secrets.JWT_SECRET_KEY }}" >> application.properties